### ISSUE TITLE
Top Priority Issue - Change Search term from mobile office to Mobile Offices & Commercial Units & only display results with that in the category or Buildings-Portable

### ISSUE THREAD

**Issue by kijami** [bkovacev/yp-listing-master#5]
I did some playing around with the api and I think this is the term we want to use

Mobile Offices & Commercial Units

**Comment by kijami** [comment]
Also we need to only display results that have this term listed in the categories

Mobile Offices & Commercial Units

**Comment by bkovacev** [comment]
Completed for the search, filtering is on the way.

**Comment by bkovacev** [comment]
Filtering completed, committing shortly.
